In [93]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import itertools
import scipy.stats
import pickle
import sys
outdir = "../../../../../data/FED/plots/01_enformer_benchmark"

## Identify tracks that are comarable btw human and mouse

In [2]:
filepath =  "/home/luisasantus/Desktop/crg_cluster/data/FED/suppl_df.pkl"
with open(filepath, 'rb') as file:
    suppl_df = pickle.load(file)

In [3]:
suppl_df_cage = suppl_df.loc[suppl_df['assay_type'] == "CAGE"]
cerebellum_targets = suppl_df_cage[suppl_df_cage["biosource"] == "cerebellum"][list(["target", "organism"])]

In [153]:
train_tracks_ind =  cerebellum_targets[cerebellum_targets.organism == "human"].index
pred_tracks_ind =  cerebellum_targets[cerebellum_targets.organism == "mouse"].index
print(len(train_tracks_ind))
print(len(pred_tracks_ind))

3
38

In [154]:
# save tracks 
# test reading 
biosource = "cerebellum"
output_dir = "/home/luisasantus/Desktop/crg_cluster/data/FED/enformer/human/mouse/pred_standard"
train_csv = os.path.join(output_dir, biosource, "train_tracks.csv")
pred_csv = os.path.join(output_dir, biosource, "pred_tracks.csv")

In [155]:
pd.DataFrame(train_tracks_ind).to_csv(train_csv, index=False)
pd.DataFrame(pred_tracks_ind).to_csv(pred_csv, index=False)

In [156]:
# read in 
pred_tracks_ind = pd.read_csv(pred_csv)
pred_tracks_ind

       0
0   1314
1   1461
2   1554
3   1555
4   1556
5   1558
6   1559
7   1560
8   1561
9   1562
10  1563
11  1564
12  1565
13  1566
14  1567
15  1568
16  1569
17  1570
18  1571
19  1572
20  1573
21  1574
22  1575
23  1576
24  1577
25  1578
26  1579
27  1580
28  1581
29  1582
30  1583
31  1584
32  1585
33  1586
34  1587
35  1588
36  1589
37  1590

## TODO 
Read in pkl predicton files
Should i do pairs or average? 
prob all the pairs in cerebellum? yes

In [108]:
# Load pickle file with predicitons
pred_chunk_file = "/home/luisasantus/Desktop/crg_cluster/data/FED/enformer/human/mouse/pred_standard/evaluation_files/valid-0-0_197k_0_pred.pkl"
with open(pred_chunk_file, 'rb') as file:
    pred = pickle.load(file)

In [109]:
# Swap axes so i can access to each track 
def swap_dim(example):
    example_tmp= (example.numpy().squeeze())
    example_swapped = np.swapaxes(example_tmp, 0,1)
    return(example_swapped)

def get_tracks(example_section, track_ids):
    example_swapped = swap_dim(example_section)
    tracks = []
    for track in track_ids: 
        tracks.append(list([track,example_swapped[track]]))
    return(tracks)

In [116]:
# Per sequence
example = pred[0]
biosource = "cerebellum"
sequence = 0

In [122]:

def eval_sequence(example): 
    # Extract ground truth for each of the training tracks
    train_targets = get_tracks(example["target"], train_tracks_ind)
    prediction_values = get_tracks(example["prediction"], pred_tracks_ind)

    # Compare them 
    targets = [];  preds = []; pearson = []
    for target in train_targets: 
        for prediction in prediction_values: 
            targets.append(target[0])
            preds.append(prediction[0])
            pearson.append(scipy.stats.pearsonr(target[1], prediction[1])[0])

    df = pd.DataFrame(list(zip(targets, preds, pearson)), columns = ["targets", "preds", "pearson"])
    return(df)

In [134]:
evaluation_df = pd.DataFrame()
for sequence, example in enumerate(pred): 
    df = eval_sequence(example)
    df["sequence"] = sequence
    evaluation_df = pd.concat([evaluation_df, df], ignore_index = True, axis = 0)

In [136]:
evaluation_df.groupby("sequence").mean("pearson")

          targets        preds   pearson
sequence
0          5123.0  1562.684211  0.090353
1          5123.0  1562.684211  0.291554
2          5123.0  1562.684211  0.881834
3          5123.0  1562.684211  0.913775
4          5123.0  1562.684211  0.812789
5          5123.0  1562.684211  0.197252
6          5123.0  1562.684211  0.199231
7          5123.0  1562.684211  0.159927
8          5123.0  1562.684211  0.373873
9          5123.0  1562.684211  0.568198
10         5123.0  1562.684211  0.377331
11         5123.0  1562.684211  0.888430
12         5123.0  1562.684211  0.254325
13         5123.0  1562.684211  0.237505
14         5123.0  1562.684211  0.199623
15         5123.0  1562.684211  0.144777
16         5123.0  1562.684211  0.144309
17         5123.0  1562.684211  0.452234
18         5123.0  1562.684211  0.181069
19         5123.0  1562.684211  0.227625
20         5123.0  1562.684211  0.099327
21         5123.0  1562.684211  0.712331
22         5123.0  1562.684211  0.565228
23         5123.0  1562.684211  0.142525
24         5123.0  1562.684211  0.300874

In [ ]:
params.evaluation_tracks = "cerebellum"
Channel.fromPath("${params.output_dir}/${params.evaluation_tracks}/train_tracks.csv").collect().set{tracks_train}
Channel.fromPath("${params.output_dir}/${params.evaluation_tracks}/pred_tracks.csv").collect().set{tracks_pred}